[package]
name = "asus-zenbook-numpad-driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evdev-rs = { version = "0.6.1", features = ["serde", "libevdev-1-10"] }
